[package]
version = "0.2.2"
edition = "2021"
authors = ["Tapish Rathore <tapish@vibinex.com>"]
sha2 = "0.10"
base64ct = "1.5.3"
sha256 = "1.1.1"
walkdir = "2"
inquire = "0.5.2"
pkg-config = "0.3.26"
reqwest = { version = "0.11", features = ["blocking", "json"] }

